### ISSUE TITLE
后台部署无法访问

### ISSUE THREAD

**Issue by lcy0828** [QXQZX/face_kaoqin_webapp#1]
有后台的技术文档嘛

**Comment by lcy0828** [comment]
在idea部署 本地能访问
但是链接不上数据库
10-Mar-2021 06:43:43.449 淇℃伅 [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
10-Mar-2021 06:43:43.482 淇℃伅 [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.ApplicationContext.log Initializing Spring root WebApplicationContext
10-Mar-2021 06:43:44.336 淇℃伅 [RMI TCP Connection(3)-127.0.0.1] org.apache.catalina.core.ApplicationContext.log Initializing Spring FrameworkServlet 'DispatcherServlet'
10-Mar-2021 06:44:13.991 涓ラ噸 [http-nio-8080-exec-8] org.apache.catalina.core.StandardWrapperValve.invoke 鍦ㄨ矾寰勪负/kaoqin_war鐨勪笂涓嬫枃涓紝Servlet[DispatcherServlet]鐨凷ervlet.service锛堬級寮曞彂浜嗗叿鏈夋牴鏈師鍥犵殑寮傚父Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.
### The error may exist in com/kaoqin/mapper/AdminMapper.xml
### The error may involve com.kaoqin.mapper.AdminMapper.loginCheck
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

Last packet sent to the server was 0 ms ago.
	java.net.ConnectException: Connection timed out: connect
		at java.net.DualStackPlainSocketImpl.connect0(Native Method)
		at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
		at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
		at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
		at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
		at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
		at java.net.Socket.connect(Socket.java:589)
		at java.net.Socket.connect(Socket.java:538)
		at java.net.Socket.<init>(Socket.java:434)
		at java.net.Socket.<init>(Socket.java:244)
		at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:253)
		at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:280)
		at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2026)
		at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
		at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
		at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
		at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
		at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1558)
		at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1623)
		at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:861)
		at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1229)
		at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:1225)
		at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:90)
		at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
		at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:77)
		at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
		at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
		at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:279)
		at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:69)
		at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:56)
		at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
		at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:141)
		at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:105)
		at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81)
		at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:101)
		at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:95)
		at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:59)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:386)
		at com.sun.proxy.$Proxy20.selectOne(Unknown Source)
		at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:165)
		at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:95)
		at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:40)
		at com.sun.proxy.$Proxy21.loginCheck(Unknown Source)
		at com.kaoqin.service.Impl.AdminServiceImpl.loginCheck(AdminServiceImpl.java:26)
		at com.kaoqin.controller.AdminController.login(AdminController.java:48)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
		at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
		at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
		at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
		at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
		at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:871)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
		at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)

**Comment by lcy0828** [comment]
导出war包到服务器，404

**Comment by devhg** [comment]
> 有后台的技术文档嘛

没有的，hxd。这就是一个写着玩的项目。我当时也没有上线部署测试。看报错，你可以检查一下数据库方面

**Comment by lcy0828** [comment]
检测过了，没得问题，用navicat能连接

**Comment by devhg** [comment]
> 检测过了，没得问题，用navicat能连接

检查代码连接数据库

**Comment by lcy0828** [comment]
好滴，我打算自己开发一个了哈哈哈哈哈
